networks:
  PrviNetwork:
    external: true

services:
  keystore-kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    command: bash /setup/setup-kibana.sh
    user: "0"
    volumes:
      - ./secrets:/secrets
      - ./setup/:/setup
    env_file:
      - ./secrets/.env.kibana.token
    networks:
      - PrviNetwork
